In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("RDC_Inventory_Core_Metrics_State_History.csv")
df

,month_date_yyyymm,state,state_id,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
0,202107,illinois,il,269900.0,-0.0004,0.0393,32216,0.0923,-0.2511,43.0,...,-0.0772,407847.5151,-0.0225,0.0703,63878,0.0031,-0.1708,0.982804,-0.1764,0.1919
1,202107,virginia,va,378999.0,-0.0026,0.0530,16402,0.1187,-0.2351,32.0,...,-0.1122,553022.6313,-0.0179,0.0776,35023,0.0099,-0.0021,1.135288,-0.2299,0.4987
2,202107,vermont,vt,350000.0,-0.0210,0.0888,1692,0.0702,-0.4540,46.0,...,-0.0562,538348.9867,-0.0319,0.1535,2809,0.0392,-0.3828,0.660165,-0.0495,0.1916
3,202107,indiana,in,239900.0,0.0019,0.0090,8009,0.1766,-0.2552,33.0,...,-0.0650,321529.0468,-0.0033,0.0496,15902,0.0782,-0.2025,0.985516,-0.1812,0.1312
4,202107,oregon,or,525000.0,0.0003,0.1564,7220,0.1365,-0.2933,33.0,...,-0.0649,711752.8358,0.0032,0.1718,18523,0.0303,-0.1643,1.565512,-0.2645,0.3960
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3107,201607,maryland,md,299900.0,NaN,NaN,27716,NaN,NaN,65.0,...,NaN,402226.9105,NaN,NaN,33605,NaN,NaN,0.212477,NaN,NaN
3108,201607,arizona,az,294900.0,NaN,NaN,31627,NaN,NaN,68.0,...,NaN,446370.9416,NaN,NaN,39656,NaN,NaN,0.253865,NaN,NaN
3109,201607,utah,ut,329900.0,NaN,NaN,13543,NaN,NaN,57.0,...,NaN,572441.4187,NaN,NaN,21574,NaN,NaN,0.593000,NaN,NaN
3110,201607,california,ca,500224.0,NaN,NaN,89335,NaN,NaN,47.0,...,NaN,931356.2570,NaN,NaN,129674,NaN,NaN,0.451548,NaN,NaN
3111,201607,montana,mt,319900.0,NaN,NaN,9500,NaN,NaN,87.0,...,NaN,543620.8883,NaN,NaN,11070,NaN,NaN,0.165263,NaN,NaN

In [7]:
print("No of rows", df.shape[0])
print("No of columns", df.shape[1])
print("Size of the Dataset", df.size)

No of rows 3112
No of columns 39
Size of the Dataset 121368

In [9]:
print(df.info)

<bound method DataFrame.info of       month_date_yyyymm       state state_id  median_listing_price  \
0                202107    illinois       il              269900.0
1                202107    virginia       va              378999.0
2                202107     vermont       vt              350000.0
3                202107     indiana       in              239900.0
4                202107      oregon       or              525000.0
...                 ...         ...      ...                   ...
3107             201607    maryland       md              299900.0
3108             201607     arizona       az              294900.0
3109             201607        utah       ut              329900.0
3110             201607  california       ca              500224.0
3111             201607     montana       mt              319900.0

      median_listing_price_mm  median_listing_price_yy  active_listing_count  \
0                     -0.0004                   0.0393                 32216
1                     -0.0026                   0.0530                 16402
2                     -0.0210                   0.0888                  1692
3                      0.0019                   0.0090                  8009
4                      0.0003                   0.1564                  7220
...                       ...                      ...                   ...
3107                      NaN                      NaN                 27716
3108                      NaN                      NaN                 31627
3109                      NaN                      NaN                 13543
3110                      NaN                      NaN                 89335
3111                      NaN                      NaN                  9500

      active_listing_count_mm  active_listing_count_yy  median_days_on_market  \
0                      0.0923                  -0.2511                   43.0
1                      0.1187                  -0.2351                   32.0
2                      0.0702                  -0.4540                   46.0
3                      0.1766                  -0.2552                   33.0
4                      0.1365                  -0.2933                   33.0
...                       ...                      ...                    ...
3107                      NaN                      NaN                   65.0
3108                      NaN                      NaN                   68.0
3109                      NaN                      NaN                   57.0
3110                      NaN                      NaN                   47.0
3111                      NaN                      NaN                   87.0

      ...  median_square_feet_yy  average_listing_price  \
0     ...                -0.0772            407847.5151
1     ...                -0.1122            553022.6313
2     ...                -0.0562            538348.9867
3     ...                -0.0650            321529.0468
4     ...                -0.0649            711752.8358
...   ...                    ...                    ...
3107  ...                    NaN            402226.9105
3108  ...                    NaN            446370.9416
3109  ...                    NaN            572441.4187
3110  ...                    NaN            931356.2570
3111  ...                    NaN            543620.8883

      average_listing_price_mm  average_listing_price_yy  total_listing_count  \
0                      -0.0225                    0.0703                63878
1                      -0.0179                    0.0776                35023
2                      -0.0319                    0.1535                 2809
3                      -0.0033                    0.0496                15902
4                       0.0032                    0.1718                18523
...                        ...                       ...                  ...
3107                       NaN                       NaN                33605
3108                       NaN                       NaN                39656
3109                       NaN                       NaN                21574
3110                       NaN                       NaN               129674
3111                       NaN                       NaN                11070

      total_listing_count_mm  total_listing_count_yy  pending_ratio  \
0                     0.0031                 -0.1708       0.982804
1                     0.0099                 -0.0021       1.135288
2                     0.0392                 -0.3828       0.660165
3                     0.0782                 -0.2025       0.985516
4                     0.0303                 -0.1643       1.565512
...                      ...                     ...            ...
3107                     NaN                     NaN       0.212477
3108                     NaN                     NaN       0.253865
3109                     NaN                     NaN       0.593000
3110                     NaN                     NaN       0.451548
3111                     NaN                     NaN       0.165263

      pending_ratio_mm  pending_ratio_yy
0              -0.1764            0.1919
1              -0.2299            0.4987
2              -0.0495            0.1916
3              -0.1812            0.1312
4              -0.2645            0.3960
...                ...               ...
3107               NaN               NaN
3108               NaN               NaN
3109               NaN               NaN
3110               NaN               NaN
3111               NaN               NaN

[3112 rows x 39 columns]>

In [10]:
df.describe()

,month_date_yyyymm,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,...,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
count,3112.000000,3112.000000,2499.00000,2499.000000,3112.000000,2499.000000,2499.000000,3112.000000,2499.000000,2499.000000,...,2485.000000,3.112000e+03,2499.000000,2499.000000,3112.000000,2499.000000,2499.000000,3112.000000,2499.000000,2499.000000
mean,201860.619537,309722.639414,0.00547,0.069576,22597.419023,-0.014784,-0.160779,71.333066,-0.002182,-0.082485,...,-0.000309,4.913809e+05,0.006064,0.080732,32240.109254,0.004923,-0.056044,0.474512,0.032421,0.231930
std,151.195701,121770.822518,0.02127,0.058155,25743.075283,0.071730,0.208003,24.389591,0.125138,0.159849,...,0.142460,2.657022e+05,0.024310,0.093208,37712.465020,0.098921,0.201976,0.481952,0.157453,0.413621
min,201607.000000,134250.000000,-0.10490,-0.227800,1.000000,-0.360200,-0.712600,7.000000,-0.508065,-0.712963,...,-1.000000,2.077657e+05,-0.120000,-0.217000,1.000000,-0.352300,-0.542400,0.000000,-0.725000,-0.845800
25%,201710.000000,224900.000000,-0.00590,0.035100,6272.750000,-0.060350,-0.295450,55.000000,-0.063074,-0.138538,...,-0.022100,2.966865e+05,-0.006800,0.029900,9002.500000,-0.039600,-0.165200,0.158694,-0.016000,0.005800
50%,201901.000000,281125.000000,0.00030,0.064400,13807.000000,-0.012600,-0.116300,68.500000,0.022472,-0.064378,...,0.001800,3.980736e+05,0.002700,0.060800,20082.000000,0.001200,-0.069600,0.317457,0.001100,0.060900
75%,202004.000000,355082.000000,0.01650,0.097850,27267.000000,0.026750,-0.027750,85.000000,0.080645,-0.010471,...,0.023300,5.958600e+05,0.017100,0.108100,38034.250000,0.042200,0.016050,0.605260,0.043400,0.346600
max,202107.000000,808908.000000,0.23640,0.378000,164441.000000,0.293300,0.844700,210.000000,0.347826,0.878788,...,3.000000,1.943105e+06,0.300500,0.795100,351391.000000,0.969600,1.770700,3.903721,2.403400,3.182600

In [11]:
df.isnull().sum()

month_date_yyyymm                            0
state                                        0
state_id                                     0
median_listing_price                         0
median_listing_price_mm                    613
median_listing_price_yy                    613
active_listing_count                         0
active_listing_count_mm                    613
active_listing_count_yy                    613
median_days_on_market                        0
median_days_on_market_mm                   613
median_days_on_market_yy                   613
new_listing_count                            0
new_listing_count_mm                       613
new_listing_count_yy                       613
price_increased_count                        0
price_increased_count_mm                   614
price_increased_count_yy                   614
price_reduced_count                          0
price_reduced_count_mm                     613
price_reduced_count_yy                     613
pending_listing_count                        0
pending_listing_count_mm                   637
pending_listing_count_yy                   642
median_listing_price_per_square_foot         0
median_listing_price_per_square_foot_mm    627
median_listing_price_per_square_foot_yy    627
median_square_feet                           0
median_square_feet_mm                      627
median_square_feet_yy                      627
average_listing_price                        0
average_listing_price_mm                   613
average_listing_price_yy                   613
total_listing_count                          0
total_listing_count_mm                     613
total_listing_count_yy                     613
pending_ratio                                0
pending_ratio_mm                           613
pending_ratio_yy                           613
dtype: int64