In [2]:
import pandas as pd
import numpy as np

In [14]:
state_df = pd.read_csv("RDC_Inventory_Core_Metrics_State_History.csv")
zip_df = pd.read_csv("RDC_Inventory_Core_Metrics_Zip_History.csv")
county_hist_df = pd.read_csv("RDC_Inventory_Hotness_Metrics_County_History.csv")

/Users/pritam/opt/anaconda3/lib/python3.8/site-packages/IPython/core/interactiveshell.py:3165: DtypeWarning: Columns (0,1) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

In [17]:
print(state_df.head(5))
print(zip_df.head(5))
print(county_hist_df.head(5))

   month_date_yyyymm     state state_id  median_listing_price  \
0             202107  illinois       il              269900.0
1             202107  virginia       va              378999.0
2             202107   vermont       vt              350000.0
3             202107   indiana       in              239900.0
4             202107    oregon       or              525000.0

   median_listing_price_mm  median_listing_price_yy  active_listing_count  \
0                  -0.0004                   0.0393                 32216
1                  -0.0026                   0.0530                 16402
2                  -0.0210                   0.0888                  1692
3                   0.0019                   0.0090                  8009
4                   0.0003                   0.1564                  7220

   active_listing_count_mm  active_listing_count_yy  median_days_on_market  \
0                   0.0923                  -0.2511                   43.0
1                   0.1187                  -0.2351                   32.0
2                   0.0702                  -0.4540                   46.0
3                   0.1766                  -0.2552                   33.0
4                   0.1365                  -0.2933                   33.0

   ...  median_square_feet_yy  average_listing_price  \
0  ...                -0.0772            407847.5151
1  ...                -0.1122            553022.6313
2  ...                -0.0562            538348.9867
3  ...                -0.0650            321529.0468
4  ...                -0.0649            711752.8358

   average_listing_price_mm  average_listing_price_yy  total_listing_count  \
0                   -0.0225                    0.0703                63878
1                   -0.0179                    0.0776                35023
2                   -0.0319                    0.1535                 2809
3                   -0.0033                    0.0496                15902
4                    0.0032                    0.1718                18523

   total_listing_count_mm  total_listing_count_yy  pending_ratio  \
0                  0.0031                 -0.1708       0.982804
1                  0.0099                 -0.0021       1.135288
2                  0.0392                 -0.3828       0.660165
3                  0.0782                 -0.2025       0.985516
4                  0.0303                 -0.1643       1.565512

   pending_ratio_mm  pending_ratio_yy
0           -0.1764            0.1919
1           -0.2299            0.4987
2           -0.0495            0.1916
3           -0.1812            0.1312
4           -0.2645            0.3960

[5 rows x 39 columns]
  month_date_yyyymm postal_code         zip_name flag  median_listing_price  \
0            202107       33029    hollywood, fl    *              589000.0
1            202107       12778    smallwood, ny  NaN              169000.0
2            202107       12309  schenectady, ny  NaN              349900.0
3            202107       74074   stillwater, ok    *              249900.0
4            202107       21128   perry hall, md    *              400000.0

   median_listing_price_mm  median_listing_price_yy  active_listing_count  \
0                  -0.0531                      NaN                  62.0
1                  -0.0315                   0.1267                  15.0
2                  -0.0266                  -0.0458                  71.0
3                   0.0038                      NaN                  62.0
4                  -0.0475                   0.0013                  14.0

   active_listing_count_mm  active_listing_count_yy  ...  \
0                   0.0333                  -0.2874  ...
1                   0.0714                  -0.1667  ...
2                   0.2456                  -0.2447  ...
3                   0.3191                  -0.4095  ...
4                  -0.1250                      NaN  ...

   median_square_feet_yy  average_listing_price  average_listing_price_mm  \
0                -0.0544            604828.8916                   -0.0577
1                -0.1950            183756.1875                    0.0315
2                -0.0506            389398.2093                   -0.0873
3                -0.0808            309726.5968                   -0.1173
4                 0.1223            449739.0455                    0.0110

   average_listing_price_yy  total_listing_count  total_listing_count_mm  \
0                    0.1723                199.0                  0.0365
1                   -0.1380                 16.0                  0.0667
2                    0.0273                226.0                  0.0089
3                   -0.1517                145.0                  0.0741
4                    0.0389                 51.0                 -0.0192

   total_listing_count_yy  pending_ratio  pending_ratio_mm  pending_ratio_yy
0                 -0.1532       2.209677            0.0097            0.5085
1                 -0.1579       0.066667           -0.0048            0.0111
2                 -0.0960       2.183099           -0.7467            0.5235
3                 -0.1104       1.338710           -0.5336            0.7863
4                  1.0400       2.642857            0.3929            2.3929

[5 rows x 40 columns]
  month_date_yyyymm county_fips     county_name  cbsa_code  \
0            202107       51033    caroline, va    40060.0
1            202107       22099  st. martin, la    29180.0
2            202107        4027        yuma, az    49740.0
3            202107       27131        rice, mn    22060.0
4            202107       55059     kenosha, wi    16980.0

                           cbsa_title  nielsen_hh_rank  hotness_rank  \
0                        richmond, va           1333.0         958.0
1                       lafayette, la            935.0        1343.0
2                            yuma, az            378.0         463.0
3            faribault-northfield, mn            864.0        1151.0
4  chicago-naperville-elgin, il-in-wi            394.0         164.0

   hotness_rank_mm  hotness_rank_yy  hotness_score  ...  median_dom_yy_day  \
0           -361.0           -207.0      43.975904  ...              -27.0
1             58.0             80.0      22.447685  ...              -78.0
2           -140.0            272.0      62.048193  ...              -32.0
3            -73.0           -785.0      34.020292  ...                0.0
4             51.0           -116.0      80.976538  ...              -15.0

   median_dom_vs_us  ldp_unique_viewers_per_property_mm  \
0               5.0                           -0.017857
1              15.0                           -0.069767
2             -11.0                           -0.371429
3               4.0                            0.000000
4             -10.0                           -0.121951

   ldp_unique_viewers_per_property_yy  ldp_unique_viewers_per_property_vs_us  \
0                            0.279070                                 1.0784
1                            0.600000                                 0.7843
2                            0.257143                                 0.8627
3                            0.205882                                 0.8039
4                           -0.027027                                 1.4118

   median_listing_price  median_listing_price_mm  median_listing_price_yy  \
0              300000.0                -0.076923                 0.034750
1              190000.0                -0.084337                -0.155556
2              285900.0                -0.010727                 0.169684
3              351400.0                -0.002838                 0.110883
4              279900.0                -0.049414                -0.125039

   median_listing_price_vs_us  quality_flag
0                      0.7792           0.0
1                      0.4935           0.0
2                      0.7426           0.0
3                      0.9127           0.0
4                      0.7270           0.0

[5 rows x 26 columns]

In [20]:
print("Details of State History File:")
print("No. of rows", state_df.shape[0])
print("No. of columns", state_df.shape[1])
print("Size of the Dataset", state_df.size)

Details of State History File:
No. of rows 3112
No. of columns 39
Size of the Dataset 121368

In [21]:
print("Details of Zip History File:")
print("No. of rows", zip_df.shape[0])
print("No. of columns", zip_df.shape[1])
print("Size of the Dataset", zip_df.size)

Details of Zip History File:
No. of rows 913084
No. of columns 40
Size of the Dataset 36523360

In [22]:
print("Details of County History File:")
print("No. of rows", county_hist_df.shape[0])
print("No. of columns", county_hist_df.shape[1])
print("Size of the Dataset", county_hist_df.size)

Details of County History File:
No. of rows 75745
No. of columns 26
Size of the Dataset 1969370

In [9]:
print(state_df.info)

<bound method DataFrame.info of       month_date_yyyymm       state state_id  median_listing_price  \
0                202107    illinois       il              269900.0
1                202107    virginia       va              378999.0
2                202107     vermont       vt              350000.0
3                202107     indiana       in              239900.0
4                202107      oregon       or              525000.0
...                 ...         ...      ...                   ...
3107             201607    maryland       md              299900.0
3108             201607     arizona       az              294900.0
3109             201607        utah       ut              329900.0
3110             201607  california       ca              500224.0
3111             201607     montana       mt              319900.0

      median_listing_price_mm  median_listing_price_yy  active_listing_count  \
0                     -0.0004                   0.0393                 32216
1                     -0.0026                   0.0530                 16402
2                     -0.0210                   0.0888                  1692
3                      0.0019                   0.0090                  8009
4                      0.0003                   0.1564                  7220
...                       ...                      ...                   ...
3107                      NaN                      NaN                 27716
3108                      NaN                      NaN                 31627
3109                      NaN                      NaN                 13543
3110                      NaN                      NaN                 89335
3111                      NaN                      NaN                  9500

      active_listing_count_mm  active_listing_count_yy  median_days_on_market  \
0                      0.0923                  -0.2511                   43.0
1                      0.1187                  -0.2351                   32.0
2                      0.0702                  -0.4540                   46.0
3                      0.1766                  -0.2552                   33.0
4                      0.1365                  -0.2933                   33.0
...                       ...                      ...                    ...
3107                      NaN                      NaN                   65.0
3108                      NaN                      NaN                   68.0
3109                      NaN                      NaN                   57.0
3110                      NaN                      NaN                   47.0
3111                      NaN                      NaN                   87.0

      ...  median_square_feet_yy  average_listing_price  \
0     ...                -0.0772            407847.5151
1     ...                -0.1122            553022.6313
2     ...                -0.0562            538348.9867
3     ...                -0.0650            321529.0468
4     ...                -0.0649            711752.8358
...   ...                    ...                    ...
3107  ...                    NaN            402226.9105
3108  ...                    NaN            446370.9416
3109  ...                    NaN            572441.4187
3110  ...                    NaN            931356.2570
3111  ...                    NaN            543620.8883

      average_listing_price_mm  average_listing_price_yy  total_listing_count  \
0                      -0.0225                    0.0703                63878
1                      -0.0179                    0.0776                35023
2                      -0.0319                    0.1535                 2809
3                      -0.0033                    0.0496                15902
4                       0.0032                    0.1718                18523
...                        ...                       ...                  ...
3107                       NaN                       NaN                33605
3108                       NaN                       NaN                39656
3109                       NaN                       NaN                21574
3110                       NaN                       NaN               129674
3111                       NaN                       NaN                11070

      total_listing_count_mm  total_listing_count_yy  pending_ratio  \
0                     0.0031                 -0.1708       0.982804
1                     0.0099                 -0.0021       1.135288
2                     0.0392                 -0.3828       0.660165
3                     0.0782                 -0.2025       0.985516
4                     0.0303                 -0.1643       1.565512
...                      ...                     ...            ...
3107                     NaN                     NaN       0.212477
3108                     NaN                     NaN       0.253865
3109                     NaN                     NaN       0.593000
3110                     NaN                     NaN       0.451548
3111                     NaN                     NaN       0.165263

      pending_ratio_mm  pending_ratio_yy
0              -0.1764            0.1919
1              -0.2299            0.4987
2              -0.0495            0.1916
3              -0.1812            0.1312
4              -0.2645            0.3960
...                ...               ...
3107               NaN               NaN
3108               NaN               NaN
3109               NaN               NaN
3110               NaN               NaN
3111               NaN               NaN

[3112 rows x 39 columns]>

In [23]:
print(zip_df.info)

<bound method DataFrame.info of                                month_date_yyyymm  \
0                                         202107
1                                         202107
2                                         202107
3                                         202107
4                                         202107
...                                          ...
913079                                    201607
913080                                    201607
913081                                    201607
913082                                    201607
913083  * year-over-year figures may be impacted

                                              postal_code         zip_name  \
0                                                   33029    hollywood, fl
1                                                   12778    smallwood, ny
2                                                   12309  schenectady, ny
3                                                   74074   stillwater, ok
4                                                   21128   perry hall, md
...                                                   ...              ...
913079                                               1245     monterey, ma
913080                                              91104     pasadena, ca
913081                                              37917    knoxville, tn
913082                                              73501       lawton, ok
913083   please contact economics@realtor.com for more...              NaN

       flag  median_listing_price  median_listing_price_mm  \
0         *              589000.0                  -0.0531
1       NaN              169000.0                  -0.0315
2       NaN              349900.0                  -0.0266
3         *              249900.0                   0.0038
4         *              400000.0                  -0.0475
...     ...                   ...                      ...
913079  NaN              699000.0                      NaN
913080  NaN              775000.0                      NaN
913081  NaN               94900.0                      NaN
913082  NaN               80000.0                      NaN
913083  NaN                   NaN                      NaN

        median_listing_price_yy  active_listing_count  \
0                           NaN                  62.0
1                        0.1267                  15.0
2                       -0.0458                  71.0
3                           NaN                  62.0
4                        0.0013                  14.0
...                         ...                   ...
913079                      NaN                  38.0
913080                      NaN                  52.0
913081                      NaN                 110.0
913082                      NaN                  70.0
913083                      NaN                   NaN

        active_listing_count_mm  active_listing_count_yy  ...  \
0                        0.0333                  -0.2874  ...
1                        0.0714                  -0.1667  ...
2                        0.2456                  -0.2447  ...
3                        0.3191                  -0.4095  ...
4                       -0.1250                      NaN  ...
...                         ...                      ...  ...
913079                      NaN                      NaN  ...
913080                      NaN                      NaN  ...
913081                      NaN                      NaN  ...
913082                      NaN                      NaN  ...
913083                      NaN                      NaN  ...

        median_square_feet_yy  average_listing_price  \
0                     -0.0544           6.048289e+05
1                     -0.1950           1.837562e+05
2                     -0.0506           3.893982e+05
3                     -0.0808           3.097266e+05
4                      0.1223           4.497390e+05
...                       ...                    ...
913079                    NaN           1.169303e+06
913080                    NaN           8.190427e+05
913081                    NaN           1.351687e+05
913082                    NaN           1.028383e+05
913083                    NaN                    NaN

        average_listing_price_mm  average_listing_price_yy  \
0                        -0.0577                    0.1723
1                         0.0315                   -0.1380
2                        -0.0873                    0.0273
3                        -0.1173                   -0.1517
4                         0.0110                    0.0389
...                          ...                       ...
913079                       NaN                       NaN
913080                       NaN                       NaN
913081                       NaN                       NaN
913082                       NaN                       NaN
913083                       NaN                       NaN

        total_listing_count  total_listing_count_mm  total_listing_count_yy  \
0                     199.0                  0.0365                 -0.1532
1                      16.0                  0.0667                 -0.1579
2                     226.0                  0.0089                 -0.0960
3                     145.0                  0.0741                 -0.1104
4                      51.0                 -0.0192                  1.0400
...                     ...                     ...                     ...
913079                 42.0                     NaN                     NaN
913080                 92.0                     NaN                     NaN
913081                177.0                     NaN                     NaN
913082                 70.0                     NaN                     NaN
913083                  NaN                     NaN                     NaN

        pending_ratio  pending_ratio_mm  pending_ratio_yy
0            2.209677            0.0097            0.5085
1            0.066667           -0.0048            0.0111
2            2.183099           -0.7467            0.5235
3            1.338710           -0.5336            0.7863
4            2.642857            0.3929            2.3929
...               ...               ...               ...
913079       0.105263               NaN               NaN
913080       0.769231               NaN               NaN
913081       0.609091               NaN               NaN
913082       0.000000               NaN               NaN
913083            NaN               NaN               NaN

[913084 rows x 40 columns]>

In [24]:
print(county_hist_df.info)

<bound method DataFrame.info of                                        month_date_yyyymm  \
0                                                 202107
1                                                 202107
2                                                 202107
3                                                 202107
4                                                 202107
...                                                  ...
75740                                             201708
75741                                             201708
75742                                             201708
75743                                             201708
75744  quality_flag = 1:  year-over-year figures may ...

                                             county_fips     county_name  \
0                                                  51033    caroline, va
1                                                  22099  st. martin, la
2                                                   4027        yuma, az
3                                                  27131        rice, mn
4                                                  55059     kenosha, wi
...                                                  ...             ...
75740                                              24037  st. mary's, md
75741                                              19113        linn, ia
75742                                              17165      saline, il
75743                                              29099   jefferson, mo
75744   please contact economics@realtor.com for more...             NaN

       cbsa_code                          cbsa_title  nielsen_hh_rank  \
0        40060.0                        richmond, va           1333.0
1        29180.0                       lafayette, la            935.0
2        49740.0                            yuma, az            378.0
3        22060.0            faribault-northfield, mn            864.0
4        16980.0  chicago-naperville-elgin, il-in-wi            394.0
...          ...                                 ...              ...
75740    15680.0       california-lexington park, md            582.0
75741    16300.0                    cedar rapids, ia            283.0
75742        NaN                                 NaN              NaN
75743    41180.0                    st. louis, mo-il            297.0
75744        NaN                                 NaN              NaN

       hotness_rank  hotness_rank_mm  hotness_rank_yy  hotness_score  ...  \
0             958.0           -361.0           -207.0      43.975904  ...
1            1343.0             58.0             80.0      22.447685  ...
2             463.0           -140.0            272.0      62.048193  ...
3            1151.0            -73.0           -785.0      34.020292  ...
4             164.0             51.0           -116.0      80.976538  ...
...             ...              ...              ...            ...  ...
75740        1011.0              NaN              NaN      39.093215  ...
75741         601.0              NaN              NaN      59.480025  ...
75742        1539.0              NaN              NaN       5.168041  ...
75743         969.0              NaN              NaN      41.280913  ...
75744           NaN              NaN              NaN            NaN  ...

       median_dom_yy_day  median_dom_vs_us  \
0                  -27.0               5.0
1                  -78.0              15.0
2                  -32.0             -11.0
3                    0.0               4.0
4                  -15.0             -10.0
...                  ...               ...
75740                NaN               6.0
75741                NaN             -21.0
75742                NaN              40.5
75743                NaN              21.0
75744                NaN               NaN

       ldp_unique_viewers_per_property_mm  ldp_unique_viewers_per_property_yy  \
0                               -0.017857                            0.279070
1                               -0.069767                            0.600000
2                               -0.371429                            0.257143
3                                0.000000                            0.205882
4                               -0.121951                           -0.027027
...                                   ...                                 ...
75740                                 NaN                                 NaN
75741                                 NaN                                 NaN
75742                                 NaN                                 NaN
75743                                 NaN                                 NaN
75744                                 NaN                                 NaN

       ldp_unique_viewers_per_property_vs_us  median_listing_price  \
0                                     1.0784              300000.0
1                                     0.7843              190000.0
2                                     0.8627              285900.0
3                                     0.8039              351400.0
4                                     1.4118              279900.0
...                                      ...                   ...
75740                                 0.7000              302400.0
75741                                 0.7000              203122.5
75742                                 0.2000               79500.0
75743                                 1.0000              194400.0
75744                                    NaN                   NaN

       median_listing_price_mm  median_listing_price_yy  \
0                    -0.076923                 0.034750
1                    -0.084337                -0.155556
2                    -0.010727                 0.169684
3                    -0.002838                 0.110883
4                    -0.049414                -0.125039
...                        ...                      ...
75740                      NaN                      NaN
75741                      NaN                      NaN
75742                      NaN                      NaN
75743                      NaN                      NaN
75744                      NaN                      NaN

       median_listing_price_vs_us  quality_flag
0                          0.7792           0.0
1                          0.4935           0.0
2                          0.7426           0.0
3                          0.9127           0.0
4                          0.7270           0.0
...                           ...           ...
75740                      1.0839           NaN
75741                      0.7280           NaN
75742                      0.2849           NaN
75743                      0.6968           NaN
75744                         NaN           NaN

[75745 rows x 26 columns]>

In [10]:
state_df.describe()

,month_date_yyyymm,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,...,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
count,3112.000000,3112.000000,2499.00000,2499.000000,3112.000000,2499.000000,2499.000000,3112.000000,2499.000000,2499.000000,...,2485.000000,3.112000e+03,2499.000000,2499.000000,3112.000000,2499.000000,2499.000000,3112.000000,2499.000000,2499.000000
mean,201860.619537,309722.639414,0.00547,0.069576,22597.419023,-0.014784,-0.160779,71.333066,-0.002182,-0.082485,...,-0.000309,4.913809e+05,0.006064,0.080732,32240.109254,0.004923,-0.056044,0.474512,0.032421,0.231930
std,151.195701,121770.822518,0.02127,0.058155,25743.075283,0.071730,0.208003,24.389591,0.125138,0.159849,...,0.142460,2.657022e+05,0.024310,0.093208,37712.465020,0.098921,0.201976,0.481952,0.157453,0.413621
min,201607.000000,134250.000000,-0.10490,-0.227800,1.000000,-0.360200,-0.712600,7.000000,-0.508065,-0.712963,...,-1.000000,2.077657e+05,-0.120000,-0.217000,1.000000,-0.352300,-0.542400,0.000000,-0.725000,-0.845800
25%,201710.000000,224900.000000,-0.00590,0.035100,6272.750000,-0.060350,-0.295450,55.000000,-0.063074,-0.138538,...,-0.022100,2.966865e+05,-0.006800,0.029900,9002.500000,-0.039600,-0.165200,0.158694,-0.016000,0.005800
50%,201901.000000,281125.000000,0.00030,0.064400,13807.000000,-0.012600,-0.116300,68.500000,0.022472,-0.064378,...,0.001800,3.980736e+05,0.002700,0.060800,20082.000000,0.001200,-0.069600,0.317457,0.001100,0.060900
75%,202004.000000,355082.000000,0.01650,0.097850,27267.000000,0.026750,-0.027750,85.000000,0.080645,-0.010471,...,0.023300,5.958600e+05,0.017100,0.108100,38034.250000,0.042200,0.016050,0.605260,0.043400,0.346600
max,202107.000000,808908.000000,0.23640,0.378000,164441.000000,0.293300,0.844700,210.000000,0.347826,0.878788,...,3.000000,1.943105e+06,0.300500,0.795100,351391.000000,0.969600,1.770700,3.903721,2.403400,3.182600

In [25]:
zip_df.describe()

,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,median_days_on_market_yy,new_listing_count,...,median_square_feet_yy,average_listing_price,average_listing_price_mm,average_listing_price_yy,total_listing_count,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy
count,9.130830e+05,714901.000000,655505.000000,913083.000000,714900.000000,656222.000000,913083.000000,714901.000000,650146.000000,913083.000000,...,669887.000000,9.130830e+05,714901.000000,714756.000000,913083.000000,714901.000000,714756.000000,913083.000000,714900.000000,714747.000000
mean,3.588742e+05,0.008641,0.066976,72.747935,0.006479,-0.069880,81.037339,0.041977,-0.022100,24.473885,...,0.021175,4.582237e+05,0.008409,0.086662,103.434069,0.019697,0.050146,0.502002,0.027384,0.209522
std,3.841025e+05,0.118361,0.198931,86.808246,0.214548,0.446134,56.314640,0.294231,0.425191,28.445996,...,6.142771,5.912597e+05,0.160828,0.316690,118.222269,0.220425,0.961373,0.718522,0.338308,0.634399
min,5.000000e+01,-0.998500,-0.999200,13.000000,-0.811200,-0.873900,0.000000,-0.977778,-0.981002,0.000000,...,-1.000000,1.650000e+03,-0.971100,-0.988600,13.000000,-0.840000,-0.907200,0.000000,-14.087700,-21.076900
25%,1.739500e+05,-0.028300,-0.033400,24.000000,-0.087000,-0.292300,47.000000,-0.114228,-0.260504,4.000000,...,-0.073000,2.094422e+05,-0.027900,-0.037600,33.000000,-0.071400,-0.213500,0.062500,-0.047900,-0.024600
50%,2.694500e+05,0.000000,0.049500,45.000000,0.000000,-0.111100,68.000000,0.047619,-0.073171,16.000000,...,0.000000,3.177581e+05,0.002900,0.053200,66.000000,0.000000,-0.050000,0.275862,0.000000,0.039300
75%,4.100000e+05,0.035400,0.145100,88.000000,0.074100,0.085100,99.000000,0.187500,0.137725,32.000000,...,0.079000,4.998780e+05,0.036300,0.162200,128.000000,0.076900,0.162600,0.641026,0.070000,0.264600
max,1.980000e+07,44.000000,21.885200,2670.000000,68.000000,65.333300,1946.500000,33.739130,12.641975,772.000000,...,4631.000000,2.620000e+07,58.702000,43.176800,3005.000000,72.000000,353.000000,24.000000,19.378400,20.538500

In [26]:
county_hist_df.describe()

,cbsa_code,nielsen_hh_rank,hotness_rank,hotness_rank_mm,hotness_rank_yy,hotness_score,supply_score,demand_score,median_days_on_market,median_days_on_market_mm,...,median_dom_yy_day,median_dom_vs_us,ldp_unique_viewers_per_property_mm,ldp_unique_viewers_per_property_yy,ldp_unique_viewers_per_property_vs_us,median_listing_price,median_listing_price_mm,median_listing_price_yy,median_listing_price_vs_us,quality_flag
count,66624.000000,66624.00000,75744.000000,56808.000000,56808.000000,75744.000000,75744.000000,75744.000000,75744.000000,56808.000000,...,56808.000000,75744.000000,56808.000000,56808.000000,75744.000000,7.574400e+04,56808.000000,56808.000000,75744.000000,56808.000000
mean,29553.695965,694.50000,787.494521,0.037724,0.402619,49.773393,49.546819,49.999967,77.423849,0.005245,...,-5.854035,12.100932,0.053382,0.714332,1.101100,2.669371e+05,0.007346,0.075332,0.841934,0.040610
std,11406.811842,400.68399,453.556467,136.082064,254.541542,24.035614,28.782614,28.886012,43.797434,0.192335,...,35.437610,41.998832,0.192044,0.783501,0.571374,1.639580e+05,0.068260,0.147521,0.512924,0.197388
min,10100.000000,1.00000,1.000000,-909.000000,-1482.000000,0.158529,0.000000,0.000000,3.000000,-0.965265,...,-286.500000,-70.000000,-0.868243,-0.818182,0.048400,3.600000e+04,-0.760939,-0.846743,0.109300,0.000000
25%,19140.000000,347.75000,395.000000,-66.000000,-129.000000,30.627774,24.603678,24.984147,52.000000,-0.088889,...,-18.500000,-9.500000,-0.066667,0.178571,0.695700,1.649000e+05,-0.018304,0.000000,0.523775,0.000000
50%,29680.000000,694.50000,788.000000,-4.000000,0.000000,50.729233,49.524413,50.000000,70.500000,0.021399,...,-6.000000,4.500000,0.000000,0.444444,1.000000,2.328143e+05,0.000385,0.058628,0.735000,0.000000
75%,39300.000000,1041.25000,1181.000000,57.000000,129.000000,68.769816,74.318326,75.015853,93.000000,0.107914,...,3.500000,24.000000,0.128205,1.107143,1.384600,3.199500e+05,0.027748,0.133384,1.002500,0.000000
max,49780.000000,1388.00000,1575.000000,1125.000000,1259.000000,99.936588,100.000000,100.000000,893.000000,6.157895,...,791.000000,855.000000,4.500000,18.250000,18.500000,2.999000e+06,5.789444,6.291667,8.327100,1.000000

In [27]:
state_df.isnull().sum()

month_date_yyyymm                            0
state                                        0
state_id                                     0
median_listing_price                         0
median_listing_price_mm                    613
median_listing_price_yy                    613
active_listing_count                         0
active_listing_count_mm                    613
active_listing_count_yy                    613
median_days_on_market                        0
median_days_on_market_mm                   613
median_days_on_market_yy                   613
new_listing_count                            0
new_listing_count_mm                       613
new_listing_count_yy                       613
price_increased_count                        0
price_increased_count_mm                   614
price_increased_count_yy                   614
price_reduced_count                          0
price_reduced_count_mm                     613
price_reduced_count_yy                     613
pending_listing_count                        0
pending_listing_count_mm                   637
pending_listing_count_yy                   642
median_listing_price_per_square_foot         0
median_listing_price_per_square_foot_mm    627
median_listing_price_per_square_foot_yy    627
median_square_feet                           0
median_square_feet_mm                      627
median_square_feet_yy                      627
average_listing_price                        0
average_listing_price_mm                   613
average_listing_price_yy                   613
total_listing_count                          0
total_listing_count_mm                     613
total_listing_count_yy                     613
pending_ratio                                0
pending_ratio_mm                           613
pending_ratio_yy                           613
dtype: int64

In [28]:
zip_df.isnull().sum()

month_date_yyyymm                               0
postal_code                                     0
zip_name                                        1
flag                                       802421
median_listing_price                            1
median_listing_price_mm                    198183
median_listing_price_yy                    257579
active_listing_count                            1
active_listing_count_mm                    198184
active_listing_count_yy                    256862
median_days_on_market                           1
median_days_on_market_mm                   198183
median_days_on_market_yy                   262938
new_listing_count                               1
new_listing_count_mm                       273008
new_listing_count_yy                       277643
price_increased_count                           1
price_increased_count_mm                   822947
price_increased_count_yy                   825303
price_reduced_count                             1
price_reduced_count_mm                     349262
price_reduced_count_yy                     333351
pending_listing_count                           1
pending_listing_count_mm                   297121
pending_listing_count_yy                   319525
median_listing_price_per_square_foot            1
median_listing_price_per_square_foot_mm    238003
median_listing_price_per_square_foot_yy    243197
median_square_feet                              1
median_square_feet_mm                      238003
median_square_feet_yy                      243197
average_listing_price                           1
average_listing_price_mm                   198183
average_listing_price_yy                   198328
total_listing_count                             1
total_listing_count_mm                     198183
total_listing_count_yy                     198328
pending_ratio                                   1
pending_ratio_mm                           198184
pending_ratio_yy                           198337
dtype: int64

In [29]:
county_hist_df.isnull().sum()

month_date_yyyymm                            0
county_fips                                  0
county_name                                  1
cbsa_code                                 9121
cbsa_title                                9121
nielsen_hh_rank                           9121
hotness_rank                                 1
hotness_rank_mm                          18937
hotness_rank_yy                          18937
hotness_score                                1
supply_score                                 1
demand_score                                 1
median_days_on_market                        1
median_days_on_market_mm                 18937
median_dom_mm_day                        18937
median_days_on_market_yy                 18937
median_dom_yy_day                        18937
median_dom_vs_us                             1
ldp_unique_viewers_per_property_mm       18937
ldp_unique_viewers_per_property_yy       18937
ldp_unique_viewers_per_property_vs_us        1
median_listing_price                         1
median_listing_price_mm                  18937
median_listing_price_yy                  18937
median_listing_price_vs_us                   1
quality_flag                             18937
dtype: int64